---
- name: Prepare AWX Build files
  hosts: localhost
  vars:
    - awx_installer_path: "/tmp/project/awx"
  tasks:
    - name: Ensure dependencies are installed.
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker apt key.
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository.
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        update_cache: true

    - name: Install Docker.
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present
        update_cache: true

    # Fix podman issue after reboot of AWX
    # https://forum.ansible.com/t/error-current-system-boot-id-differs-from-cached-boot-id/7898
    # https://github.com/containers/podman/discussions/23193
    - name: Extend entrypoint.sh to fix podman issue after reboot of AWX
      lineinfile:
        path: "{{awx_installer_path}}/tools/docker-compose/entrypoint.sh"
        insertafter: '#!/bin/bash'
        line: "{{ item }}"
      loop:
        - " "
        - "rm -rf /run/containers/storage && rm -rf /run/libpod"
        - "echo 'Cleanup podman directories to avoid startup issues after reboot'"

    - name: Enable Use_container_for_build
      replace:
        path: "{{awx_installer_path}}/tools/docker-compose/inventory"
        regexp: '# use_container_for_build=true'
        replace: 'use_container_for_build=false'
