---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  python_interpreter:
    package_system: python39  # (optional) name of a Python interpreter OS package to install
    python_path: /usr/bin/python3.9  # (optional) path to the Python interpreter to use
  ansible_core:
    package_pip: ansible-core==2.15.12
  ansible_runner:
    package_pip: ansible-runner
  system: bindep.txt
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend_base: |
    RUN dnf install -y git
    RUN dnf config-manager --set-enabled crb
    RUN dnf install -y epel-release epel-next-release
    #    RUN /usr/bin/python3 -m pip install --upgrade pip
  append_base: |
    RUN $PYCMD -m pip install -U pip
    RUN dnf install -y git